context:
  name: synspace
  version: 0.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/synspace-${{ version }}.tar.gz
  sha256: d0e004041e8e9ea401b699241d8f18574d8a4893e179260316ff8e5d1ff67515

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - rdkit
    - tqdm
    - numpy
    - importlib-resources
    - requests
    - pandas
    - pystow
    - skunk

tests:
  - python:
      imports:
        - synspace
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Generative model based on forward synthesis rules
  license: MIT
  license_file:
    - LICENSE
    - NOTICE.txt
  homepage: https://github.com/whitead/synspace

extra:
  recipe-maintainers:
    - hadim
